#!/bin/bash
#PBS -l nodes=19:ppn=12
#PBS -l walltime=00:10:00
#PBS -q batch
#PBS -N mc
#PBS -j oe

cd /home/rawsonb/LA5
for i in `seq 1 10`; do
    mpiexec -np 19 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./mc.cx $i
done