#!/bin/bash
#PBS -l nodes=1:ppn=12
#PBS -l walltime=00:10:00
#PBS -q batch
#PBS -N Matrix-Matrix-Multiplication
#PBS -j oe

cd /home/rawsonb/PA1
for i in `seq 1 20`; do
	export OMP_NUM_THREADS=$i
	./mmp.cx 1300
done