#!/bin/bash
#PBS -l nodes=5:ppn=12
#PBS -l walltime=00:10:00
#PBS -q batch
#PBS -N ping_pong
#PBS -j oe

cd /home/rawsonb/PA2
mpiexec -np 5 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./ping_pong.cx
